# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-Main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build_testenvironment:
    name: ${{ matrix.os }} - Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 18, 20, 21]       
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}     
    - name: Check node version
      run: node -v
    - run: pwd  
    - name: Install dependencies
      run: npm ci
    - run: npm init -y   
    - name: Setup gauge
      run: npm install -g @getgauge/cli
    - run: gauge install js    
    - name: Install Playwright Lib + Browser
      run: npm i -D playwright @playwright/browser-chromium @playwright/browser-firefox @playwright/browser-webkit
    - name: Reinstall gauge Cli
      run: npm install -g @getgauge/cli
